### ISSUE TITLE
Hi Eugene, 

### ISSUE THREAD

**Issue by lapism** [EugeneHoran/Android-ViewPager-Fragment-Example#1]
Hi, this is new link for my project: https://github.com/lapism/SearchView
If you wanna change some part, just fork it. Or you wanna be a collaborator? :)

**Comment by EugeneHoran** [comment]
I was wondering what happened to the project. Once I get a chance I will
work on improving some things. Very busy at work lately. Should get some
free time this week. I will pull it then mess around with it till I get it
right.

**Comment by lapism** [comment]
Nothing happened. Only I decided to change my GitHub profile name ( now it is more like my name ). and after that I had to change a lot of things :). OK, I will look forward for improvements.
